database:
  host: localhost
  port: 5433
  user: postgres
  password: postgres
  dbname: airfaucet
  sslmode: disable

server:
  port: 3000
  cors:
    allowed_origins:
      - http://localhost:8080
    allowed_methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed_headers:
      - Origin
      - Content-Type 